# Generated by Django 4.2.7 on 2023-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='fill', max_length=10, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
